server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/bff/ {
    proxy_pass http://backend-bff:8080/api/bff/;
    proxy_set_header Host $host;
    proxy_set_header Authorization $http_authorization;
  }

  location /api/ {
    proxy_pass http://backend-core:8080/api/;
    proxy_set_header Host $host;
    proxy_set_header Authorization $http_authorization;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
